import type { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import MainLayout from "../../components/templates/MainLayout/MainLayout.component";
import "../globals.css";
import { getLocale } from "@/src/lib/i18n/config";
import ReduxProvider from "@/src/components/templates/Provider/Provider";
import { QueryProvider } from "@/src/components/templates/QueryProvider/QueryProvider";
import { futuraFont } from "@/src/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternates: {
    canonical: "./",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={`${futuraFont.variable} antialiased relative`}>
        <ReduxProvider>
          <QueryProvider>
            <NextIntlClientProvider messages={messages}>
              <MainLayout>{children}</MainLayout>
            </NextIntlClientProvider>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
